### ISSUE TITLE
Link to images in Readme.MD provide error

### ISSUE THREAD

**Issue by 4x10m** [stefanceriu/SCStackViewController#11]
Hi, the link: https://camo.githubusercontent.com/4cc139b7a30d6ba4dfae5228d7d63bfb8ae93632/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f31323734383230312f5265636f7264696e67732f5343537461636b56696577436f6e74726f6c6c65722f76332e322e302f536964654d656e757344656d6f2e676966 which i find under images in the readme provide the following error: Content length exceeded
Regards.

**Comment by stefanceriu** [comment]
Hey, thanks for raising this.

Seems like camo doesn't like them anymore and I assume it's because they're above a certain size.
I tried purging them from the cache but it didn't seem to do the trick so it's either making them smaller or adding them to the repo (which I'm reluctant to do).

Please refer to the original links while I try to figure this out:

##### Top stacked view controllers with elastic ease out easing function and perspective transform
https://dl.dropboxusercontent.com/u/12748201/Recordings/SCStackViewController/v3.2.0/ImagesDemo.gif

##### Side stacked with parallax and root resizing
https://dl.dropboxusercontent.com/u/12748201/Recordings/SCStackViewController/v3.2.0/SideMenusDemo.gif

##### Title bar with custom navigation steps and a bounce ease out easing function
https://dl.dropboxusercontent.com/u/12748201/Recordings/SCStackViewController/v3.2.0/TitleBarDemo.gif

#### A modal view controller using a scale and rotation transform
https://dl.dropboxusercontent.com/u/12748201/Recordings/SCStackViewController/v3.2.0/ModalDemo.gif

Cheers,
Stefan

**Comment by stefanceriu** [comment]
Hey, 

I finally managed to migrate everything from dropbox public folders (they're going away and I kept postponing it) to google drive and it seems that did the trick.

Cheers,
Stefan
